export { default as IdentifierField } from "./IdentifierField.vue"
export { default as PasswordField } from "./PasswordField.vue"
export { default as PhoneField } from "./PhoneField.vue"
export { default as CodeField } from "./CodeField.vue"
export { default as NameFiend } from "./NameField.vue"